"use client";

import { ArrowRight, FlaskConical, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { ErrorState } from "@/components/error-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { boundedInteger, orderLink, resultLabel, runCheckout, runDuplicate, runInventory, runProvider, type CheckoutResult, type DuplicateResult, type ExperimentKind, type ExperimentResult, type InventoryResult, type ProviderResult } from "@/lib/experiment-api";

const experiments = [
  { id: "inventory" as const, title: "Inventory Contention", description: "Race many buyers against limited inventory.", demonstrates: "PostgreSQL conditional update · no overselling", invariant: "available_quantity >= 0" },
  { id: "checkout" as const, title: "Checkout Idempotency", description: "Race checkout calls using one cart and one key.", demonstrates: "advisory lock · persistent idempotency", invariant: "persisted checkout mappings = 1" },
  { id: "provider" as const, title: "Provider Idempotency", description: "Race authorization RPCs using one provider request ID.", demonstrates: "provider advisory lock · stable result", invariant: "one stable logical provider result" },
  { id: "duplicate" as const, title: "Duplicate Event Processing", description: "Process one event identity repeatedly through the receipt primitive.", demonstrates: "ON CONFLICT · persistent receipt", invariant: "consumer receipts = 1" },
];

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{label}</dt><dd className="mt-1 break-all font-mono text-sm">{value}</dd></div>; }
function NumberField({ label, value, set, min, max }: { label: string; value: number; set: (n: number) => void; min: number; max: number }) { return <label className="block text-xs text-muted-foreground">{label}<Input className="mt-1" type="number" value={value} min={min} max={max} onChange={(e) => set(Number(e.target.value))} /></label>; }

export function ConcurrencyLab() {
  const [selected, setSelected] = useState<ExperimentKind>("inventory");
  const [workers, setWorkers] = useState(100); const [inventory, setInventory] = useState(10); const [quantity, setQuantity] = useState(1); const [attempts, setAttempts] = useState(2);
  const [running, setRunning] = useState(false); const [result, setResult] = useState<ExperimentResult | null>(null); const [error, setError] = useState<string | null>(null);
  const definition = experiments.find((item) => item.id === selected)!;
  const activeCount = selected === "duplicate" ? attempts : workers;
  const valid = boundedInteger(activeCount, 2, 200) && (selected !== "inventory" || (boundedInteger(inventory, 0, 10_000) && boundedInteger(quantity, 1, 100)));
  async function run() {
    setRunning(true); setResult(null); setError(null);
    try {
      const next = selected === "inventory" ? await runInventory({ initialInventory: inventory, workers, quantityPerWorker: quantity }) : selected === "checkout" ? await runCheckout(workers) : selected === "provider" ? await runProvider(workers) : await runDuplicate(attempts);
      setResult(next);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Experiment request failed."); } finally { setRunning(false); }
  }
  return <div className="min-w-0 space-y-5">
    <PageHeader title="Concurrency Lab" description="Run controlled concurrent workloads against CommerceCore and inspect persisted invariant evidence." />
    <div className="flex gap-3 rounded-md border border-amber-900/70 bg-amber-950/15 p-3 text-xs text-amber-100"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><div><p className="font-medium">Development control</p><p className="mt-1 leading-5 text-amber-200/75">Concurrency Lab creates real CommerceCore state and intentionally executes concurrent operations. It is a correctness laboratory, not a load benchmark.</p></div></div>
    <section><h2 className="mb-2 border-b border-border pb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Experiments</h2><div className="grid gap-3 md:grid-cols-2">{experiments.map((item) => <Card key={item.id} className={selected === item.id ? "border-blue-700" : ""}><CardHeader><div className="flex justify-between gap-3"><div><CardTitle>{item.title}{item.id === "inventory" && <span className="ml-2 text-[9px] text-blue-400">RECOMMENDED</span>}</CardTitle><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.description}</p></div><FlaskConical className="size-4 shrink-0 text-muted-foreground" /></div></CardHeader><CardContent><p className="mb-4 text-xs">{item.demonstrates}</p><Button variant={selected === item.id ? "default" : "outline"} size="sm" onClick={() => { setSelected(item.id); setResult(null); setError(null); setWorkers(item.id === "inventory" ? 100 : 20); }}>{selected === item.id ? "Configured" : "Configure"}</Button></CardContent></Card>)}</div></section>
    <Card><CardHeader><CardTitle>Configure {definition.title}</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{selected === "inventory" && <NumberField label="Initial inventory" value={inventory} set={setInventory} min={0} max={10000} />}<NumberField label={selected === "inventory" ? "Concurrent buyers" : selected === "duplicate" ? "Requested processing attempts" : "Concurrent requests"} value={activeCount} set={selected === "duplicate" ? setAttempts : setWorkers} min={2} max={200} />{selected === "inventory" && <NumberField label="Quantity each" value={quantity} set={setQuantity} min={1} max={100} />}</div><div className="grid gap-4 border-y border-border py-4 sm:grid-cols-2"><div><p className="text-xs font-medium">What will happen</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{definition.description} The backend prepares isolated state, releases coordinated workers, waits with a timeout, then reads persisted state.</p></div><div><p className="text-xs font-medium">Invariant being tested</p><p className="mt-1 font-mono text-xs text-blue-300">{definition.invariant}</p></div></div>{!valid && <p className="text-xs text-red-300">Use whole numbers within the displayed safe bounds.</p>}<Button onClick={() => void run()} disabled={running || !valid}>{running ? `Experiment running — coordinating ${activeCount} workers…` : "Run experiment"}</Button></CardContent></Card>
    {error && <ErrorState message={`Experiment API failure: ${error}`} />}
    {result && <ResultPanel kind={selected} result={result} />}
  </div>;
}

function ResultPanel({ kind, result }: { kind: ExperimentKind; result: ExperimentResult }) {
  const label = resultLabel(result); const tone = label === "PASS" ? "success" : label === "FAIL" ? "danger" : "warning";
  return <section className="space-y-3"><div className="flex items-center justify-between border-b border-border pb-2"><h2 className="text-[10px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Experiment result</h2><StatusBadge tone={tone}>{label}</StatusBadge></div><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader><CardTitle>Configuration & observed outcomes</CardTitle></CardHeader><CardContent><dl className="grid grid-cols-2 gap-4"><Metric label="Experiment" value={result.experimentId} /><Metric label="Duration" value={`${result.durationMs} ms`} />{kind === "inventory" && <InventoryObserved result={result as InventoryResult} />}{kind === "checkout" && <CheckoutObserved result={result as CheckoutResult} />}{kind === "provider" && <ProviderObserved result={result as ProviderResult} />}{kind === "duplicate" && <DuplicateObserved result={result as DuplicateResult} />}</dl></CardContent></Card><Card><CardHeader><CardTitle>Authoritative final state & invariant evidence</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-xs leading-5 text-muted-foreground">{result.complete ? "Every coordinated worker returned before the backend deadline." : "Execution was incomplete; invariant success is not inferred."}</p>{kind === "inventory" && <InventoryFinal result={result as InventoryResult} />}{kind === "checkout" && <CheckoutFinal result={result as CheckoutResult} />}{kind === "provider" && <ProviderFinal result={result as ProviderResult} />}{kind === "duplicate" && <DuplicateFinal result={result as DuplicateResult} />}<div className="border-t border-border pt-3"><StatusBadge tone={tone}>{label}</StatusBadge><p className="mt-2 text-xs text-muted-foreground">Derived from the raw observed outcomes and authoritative persisted/read-back evidence above; failure remains visible.</p></div></CardContent></Card></div></section>;
}
function InventoryObserved({ result: r }: { result: InventoryResult }) { return <><Metric label="Workers" value={r.workers} /><Metric label="Initial / quantity" value={`${r.initialInventory} / ${r.quantityPerWorker}`} /><Metric label="Succeeded" value={r.successful} /><Metric label="Rejected" value={r.rejected} /></>; }
function InventoryFinal({ result: r }: { result: InventoryResult }) { const total=Math.max(1,r.workers); return <><dl className="grid grid-cols-2 gap-4"><Metric label="Persisted inventory" value={r.finalInventory} /><Metric label="Generated SKU" value={r.sku} /></dl><div className="mt-4 flex h-2 overflow-hidden rounded bg-red-900/60"><span className="bg-emerald-500" style={{width:`${r.successful/total*100}%`}} /></div><p className="mt-2 font-mono text-xs">available_quantity &gt;= 0</p><p className="mt-1 text-[11px] text-muted-foreground">Final-state evidence does not claim continuous observation of every intermediate value.</p></>; }
function CheckoutObserved({ result: r }: { result: CheckoutResult }) { return <><Metric label="Requests" value={r.workers} /><Metric label="Successful / failed" value={`${r.successfulResponses} / ${r.failedResponses}`} /><Metric label="Distinct response orders" value={r.distinctResponseOrderIds.length} /><Metric label="Idempotency key" value={r.idempotencyKey} /></>; }
function CheckoutFinal({ result: r }: { result: CheckoutResult }) { const id=r.distinctResponseOrderIds[0]; return <><dl className="grid grid-cols-2 gap-4"><Metric label="Persisted mappings for cart" value={r.persistedMappingsForCart} /><Metric label="Cart" value={r.cartId} /></dl>{id && <Link className="mt-4 inline-flex items-center gap-2 text-sm text-blue-400" href={orderLink(id)}>Inspect Order <ArrowRight className="size-4" /></Link>}</>; }
function ProviderObserved({ result: r }: { result: ProviderResult }) { return <><Metric label="Requests" value={r.workers} /><Metric label="Successful / failed" value={`${r.successfulResponses} / ${r.failedResponses}`} /><Metric label="Distinct logical results" value={r.distinctLogicalResults.length} /><Metric label="Provider request" value={r.providerRequestId} /></>; }
function ProviderFinal({ result: r }: { result: ProviderResult }) { return <dl className="grid grid-cols-2 gap-4"><Metric label="Lookup status" value={r.authoritativeProviderStatus} /><Metric label="Provider reference" value={r.providerReference ?? "—"} /></dl>; }
function DuplicateObserved({ result: r }: { result: DuplicateResult }) { return <><Metric label="Attempts requested" value={r.attempts} /><Metric label="New receipt inserts" value={r.newlyPersistedReceipts} /><Metric label="Event ID" value={r.eventId} /></>; }
function DuplicateFinal({ result: r }: { result: DuplicateResult }) { return <><Metric label="Persisted receipt count" value={r.authoritativeReceiptCount} /><p className="mt-3 text-[11px] text-muted-foreground">This synthetic receipt identity has no corresponding outbox event to inspect. Attempts requested are direct calls to the same receipt primitive used by the proof consumer, not a physical Kafka delivery count.</p></>; }
